
#define LAMP_SHOOT_AGAIN            0
#define LAMP_DOUBLE_TIMER_OUTLANES  1
#define LAMP_5_DROP_LIGHTS_OUTLANES 2
#define LAMP_RIGHT_POP              3
#define LAMP_SPINNER_AND_LOWER_POP  4
#define LAMP_TOP_POP                5
#define LAMP_LEFT_SAUCER            6
#define LAMP_RIGHT_SAUCER           7
#define LAMP_LEFT_1K                8
#define LAMP_LEFT_2K                9
#define LAMP_LEFT_3K                10
#define LAMP_LEFT_4K                11
#define LAMP_LEFT_5K                12
#define LAMP_LEFT_6K                13
#define LAMP_LEFT_7K                14
#define LAMP_LEFT_8K                15
#define LAMP_LEFT_9K                16
#define LAMP_LEFT_10K               17
#define LAMP_RIGHT_1K               18
#define LAMP_RIGHT_2K               19
#define LAMP_RIGHT_3K               20
#define LAMP_RIGHT_4K               21
#define LAMP_RIGHT_5K               22
#define LAMP_RIGHT_6K               23
#define LAMP_RIGHT_7K               24
#define LAMP_RIGHT_8K               25
#define LAMP_RIGHT_9K               26
#define LAMP_RIGHT_10K              27
#define LAMP_COLLECT_DOUBLE_TIMER   28
#define LAMP_INLANE_SPECIAL         29
#define LAMP_INLANE_50k             30
#define LAMP_INLANE_EXTRA_BALL      31
#define LAMP_BONUS_2X               32
#define LAMP_BONUS_3X               33
#define LAMP_BONUS_5X               34
#define LAMP_3_DROPS_10K            35
#define LAMP_3_DROPS_20K            36
#define LAMP_3_DROPS_30K            37
#define LAMP_3_DROPS_50K            38
#define LAMP_3_DROPS_SPECIAL        39
#define LAMP_HEAD_LEFT_TIMER        40
#define LAMP_4_TOP_LANE             41
#define LAMP_5_TOP_LANE             42
#define LAMP_6_TOP_LANE             43
#define LAMP_1_STANDUP              44
#define LAMP_2_STANDUP              45
#define LAMP_3_STANDUP              46
#define LAMP_HEAD_BALL_IN_PLAY_4            47
#define LAMP_HEAD_RIGHT_TIMER               48
#define LAMP_HEAD_1_PLAYER                  49
#define LAMP_HEAD_2_PLAYERS                 50
#define LAMP_HEAD_3_PLAYERS                 51
#define LAMP_HEAD_4_PLAYERS                 52
#define LAMP_HEAD_MATCH                     53
#define LAMP_HEAD_BALL_IN_PLAY              54
#define LAMP_APRON_CREDITS                  55
#define LAMP_HEAD_PLAYER_1_UP               56
#define LAMP_HEAD_PLAYER_2_UP               57
#define LAMP_HEAD_PLAYER_3_UP               58
#define LAMP_HEAD_PLAYER_4_UP               59
#define LAMP_HEAD_TILT                      60
#define LAMP_HEAD_GAME_OVER                 61
#define LAMP_HEAD_SAME_PLAYER_SHOOTS_AGAIN  62
#define LAMP_HEAD_HIGH_SCORE                63


#define SW_PLUMB_TILT             0
#define SW_ROLL_TILT              1
#define SW_CREDIT_RESET           2
#define SW_COIN_1                 3
#define SW_COIN_2                 4
#define SW_COIN_3                 5
#define SW_SLAM                   6
#define SW_HIGH_SCORE_RESET       7 
#define SW_BALL_1                 8
#define SW_BALL_2                 9
#define SW_LEFT_SAUCER            10
#define SW_RIGHT_SAUCER           11
#define SW_PLAYFIELD_TILT         12
#define SW_LEFT_OUTLANE           13
#define SW_RIGHT_OUTLANE          14
#define SW_OUTHOLE                15
#define SW_RIGHT_FLIPPER          16
#define SW_LEFT_CENTER_INLANE     17
#define SW_LEFT_INSIDE_INLANE     18
#define SW_RIGHT_INSIDE_INLANE    19
#define SW_RIGHT_CENTER_INLANE    20
#define SW_RIGHT_POP_BUMPER       21
#define SW_LOWER_POP_BUMPER       22
#define SW_UPPER_POP_BUMPER       23
#define SW_LEFT_3_DROP_1          24
#define SW_LEFT_3_DROP_2          25
#define SW_LEFT_3_DROP_3          26
#define SW_RIGHT_3_DROP_1         27
#define SW_RIGHT_3_DROP_2         28
#define SW_RIGHT_3_DROP_3         29
#define SW_3_DROPS_COMPLETE       30
#define SW_SPINNER                31
#define SW_5_DROP_1               32
#define SW_5_DROP_2               33
#define SW_5_DROP_3               34
#define SW_5_DROP_4               35
#define SW_5_DROP_5               36
#define SW_5_DROP_COMPLETE        37
#define SW_LEFT_SLING             38
#define SW_RIGHT_SLING            39
#define SW_LEFT_BULLSEYE          40
#define SW_RIGHT_BULLSEYE         41
#define SW_1_TARGET               42
#define SW_2_TARGET               43
#define SW_3_TARGET               44
#define SW_4_ROLLOVER             45
#define SW_5_ROLLOVER             46
#define SW_6_ROLLOVER             47
#define SW_RIGHT_LANE_TO_TOP      48
#define SW_UPPER_LEFT_10          49
#define SW_LEFT_3_DROP_10         50
#define SW_RIGHT_3_DROP_10        51
#define SW_CENTER_LEFT_10         52
#define SW_5_DROP_10              53
#define SW_CENTER_RIGHT_10        54
#define SW_UPPER_RIGHT_10         55
#define SW_LOWER_RIGHT_10         57


#define SOL_OUTHOLE                 0
#define SOL_5_DROP_LEFT_RESET       1
#define SOL_5_DROP_RIGHT_RESET      2
#define SOL_3_DROP_LEFT_RESET       3
#define SOL_3_DROP_RIGHT_RESET      4
#define SOL_BALL_RAMP_THROWER       5
#define SOL_LEFT_SAUCER             6
#define SOL_RIGHT_SAUCER            7
#define SOL_KNOCKER                 13
#define SOL_GI_RELAY                14
#define SOLCONT_COIN_LOCKOUT        15

#define SOL_BOTTOM_POP              16
#define SOL_TOP_POP                 17
#define SOL_RIGHT_POP               18
#define SOL_LEFT_SLING              20
#define SOL_RIGHT_SLING             21
